##you can test your requests with rest client in here
##simply add your request here and "send request" button will appear
## use "##" to add another request.
##follow the steps below to create a new magazine then delete it

###
GET http://localhost:10000/




### 
GET http://localhost:10000/showcart/1

###
GET http://localhost:10000/listcarts

###
GET http://localhost:10000/listcartitems

###
GET http://localhost:10000/listproducts

###
GET http://localhost:10000/listcustomers

###
POST http://localhost:10000/addtocart/1/10

###
DELETE http://localhost:10000/deletecartitem/1/10


