DROP TABLE IF EXISTS CART_ITEMS;
DROP TABLE IF EXISTS CARTS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE `CUSTOMERS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL,
	`BALANCE` FLOAT,
	`CONSECUTIVE_DISCOUNT` INT NOT NULL DEFAULT '0',
	`HAS_SUBSEQUENT_DISCOUNT_UNTIL` DATE DEFAULT '1900-01-01',
	PRIMARY KEY (`ID`)
);

CREATE TABLE `CARTS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`CUSTOMER_ID` INT,
	`IS_PURCHASED` BOOLEAN DEFAULT '0',
	`DATE_PURCHASED` DATE NOT NULL,
	`TOTAL_PRICE` FLOAT NOT NULL DEFAULT '0',
	`DISCOUNT` FLOAT NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
);

CREATE TABLE `CART_ITEMS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`CART_ID` INT NOT NULL,
	`PRODUCT_ID` INT NOT NULL,
	`PRODUCT_NAME` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `PRODUCTS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL,
	`PRICE` FLOAT NOT NULL,
	`VAT` FLOAT NOT NULL,
	PRIMARY KEY (`ID`)
);

ALTER TABLE `CARTS` ADD CONSTRAINT `CARTS_fk0` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMERS`(`ID`);

ALTER TABLE `CART_ITEMS` ADD CONSTRAINT `CART_ITEMS_fk0` FOREIGN KEY (`CART_ID`) REFERENCES `CARTS`(`ID`);

ALTER TABLE `CART_ITEMS` ADD CONSTRAINT `CART_ITEMS_fk1` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS`(`ID`);

INSERT INTO products(name,price,vat) VALUES ("wooden spoon",90,0.01);
INSERT INTO products(name,price,vat) VALUES ("chain",90,0.01);
INSERT INTO products(name,price,vat) VALUES ("plush unicorn",6,0.01);
INSERT INTO products(name,price,vat) VALUES ("beaded necklace",22,0.01);
INSERT INTO products(name,price,vat) VALUES ("rubber band",62,0.01);
INSERT INTO products(name,price,vat) VALUES ("fishing hook",91,0.01);
INSERT INTO products(name,price,vat) VALUES ("cellphone",82,0.01);
INSERT INTO products(name,price,vat) VALUES ("jar of peanut butter",6,0.01);
INSERT INTO products(name,price,vat) VALUES ("clock",2,0.01);
INSERT INTO products(name,price,vat) VALUES ("few batteries",45,0.01);
INSERT INTO products(name,price,vat) VALUES ("package of glitter",98,0.01);
INSERT INTO products(name,price,vat) VALUES ("squirrel",82,0.01);
INSERT INTO products(name,price,vat) VALUES ("shirt button",4,0.01);
INSERT INTO products(name,price,vat) VALUES ("paper",6,0.01);
INSERT INTO products(name,price,vat) VALUES ("tube of lip balm",93,0.01);
INSERT INTO products(name,price,vat) VALUES ("nail filer",21,0.01);
INSERT INTO products(name,price,vat) VALUES ("mop",2,0.01);
INSERT INTO products(name,price,vat) VALUES ("sticky note",89,0.01);
INSERT INTO products(name,price,vat) VALUES ("whistle",21,0.01);
INSERT INTO products(name,price,vat) VALUES ("basketball",21,0.01);
INSERT INTO products(name,price,vat) VALUES ("key chain",8,0.01);
INSERT INTO products(name,price,vat) VALUES ("pocketknife",94,0.01);
INSERT INTO products(name,price,vat) VALUES ("paint brush",34,0.01);
INSERT INTO products(name,price,vat) VALUES ("crow",89,0.01);
INSERT INTO products(name,price,vat) VALUES ("harmonica",97,0.01);
INSERT INTO products(name,price,vat) VALUES ("sandal",83,0.01);
INSERT INTO products(name,price,vat) VALUES ("umbrella",96,0.01);
INSERT INTO products(name,price,vat) VALUES ("bottle of water",11,0.08);
INSERT INTO products(name,price,vat) VALUES ("card",65,0.08);
INSERT INTO products(name,price,vat) VALUES ("tube of lipstick",34,0.08);
INSERT INTO products(name,price,vat) VALUES ("rusty nail",12,0.08);
INSERT INTO products(name,price,vat) VALUES ("jigsaw puzzle",91,0.08);
INSERT INTO products(name,price,vat) VALUES ("plastic fork",14,0.08);
INSERT INTO products(name,price,vat) VALUES ("steak knife",73,0.08);
INSERT INTO products(name,price,vat) VALUES ("garden spade",49,0.08);
INSERT INTO products(name,price,vat) VALUES ("children's book",40,0.08);
INSERT INTO products(name,price,vat) VALUES ("car",27,0.08);
INSERT INTO products(name,price,vat) VALUES ("face wash",11,0.08);
INSERT INTO products(name,price,vat) VALUES ("white out",72,0.08);
INSERT INTO products(name,price,vat) VALUES ("sharpie",96,0.08);
INSERT INTO products(name,price,vat) VALUES ("mobile phone",59,0.08);
INSERT INTO products(name,price,vat) VALUES ("bowl",71,0.08);
INSERT INTO products(name,price,vat) VALUES ("photo album",56,0.08);
INSERT INTO products(name,price,vat) VALUES ("ladle",38,0.08);
INSERT INTO products(name,price,vat) VALUES ("toy boat",8,0.08);
INSERT INTO products(name,price,vat) VALUES ("radio",64,0.08);
INSERT INTO products(name,price,vat) VALUES ("socks",31,0.08);
INSERT INTO products(name,price,vat) VALUES ("cup",97,0.08);
INSERT INTO products(name,price,vat) VALUES ("glow stick",26,0.08);
INSERT INTO products(name,price,vat) VALUES ("catalogue",1,0.08);
INSERT INTO products(name,price,vat) VALUES ("needle",98,0.08);
INSERT INTO products(name,price,vat) VALUES ("stick of incense",26,0.08);
INSERT INTO products(name,price,vat) VALUES ("egg beater",69,0.08);
INSERT INTO products(name,price,vat) VALUES ("ice cream stick",61,0.08);
INSERT INTO products(name,price,vat) VALUES ("boom box",57,0.08);
INSERT INTO products(name,price,vat) VALUES ("cars",81,0.08);
INSERT INTO products(name,price,vat) VALUES ("bottle of syrup",5,0.08);
INSERT INTO products(name,price,vat) VALUES ("toothpick",97,0.08);
INSERT INTO products(name,price,vat) VALUES ("baseball bat",47,0.08);
INSERT INTO products(name,price,vat) VALUES ("snowglobe",45,0.08);
INSERT INTO products(name,price,vat) VALUES ("whale",45,0.08);
INSERT INTO products(name,price,vat) VALUES ("toothbrush",61,0.08);
INSERT INTO products(name,price,vat) VALUES ("bangle bracelet",50,0.08);
INSERT INTO products(name,price,vat) VALUES ("phone",3,0.08);
INSERT INTO products(name,price,vat) VALUES ("shoe lace",30,0.08);
INSERT INTO products(name,price,vat) VALUES ("sofa",66,0.08);
INSERT INTO products(name,price,vat) VALUES ("mp3 player",36,0.08);
INSERT INTO products(name,price,vat) VALUES ("shampoo",41,0.08);
INSERT INTO products(name,price,vat) VALUES ("plush pony",100,0.08);
INSERT INTO products(name,price,vat) VALUES ("notepad",18,0.08);
INSERT INTO products(name,price,vat) VALUES ("floor",81,0.08);
INSERT INTO products(name,price,vat) VALUES ("rubber stamp",71,0.18);
INSERT INTO products(name,price,vat) VALUES ("wrench",40,0.18);
INSERT INTO products(name,price,vat) VALUES ("seat belt",54,0.18);
INSERT INTO products(name,price,vat) VALUES ("water bottle",35,0.18);
INSERT INTO products(name,price,vat) VALUES ("hair pin",61,0.18);
INSERT INTO products(name,price,vat) VALUES ("bottle of sunscreen",2,0.18);
INSERT INTO products(name,price,vat) VALUES ("house",79,0.18);
INSERT INTO products(name,price,vat) VALUES ("plush cat",96,0.18);
INSERT INTO products(name,price,vat) VALUES ("wine glass",66,0.18);
INSERT INTO products(name,price,vat) VALUES ("microphone",15,0.18);
INSERT INTO products(name,price,vat) VALUES ("pants",72,0.18);
INSERT INTO products(name,price,vat) VALUES ("bananas",28,0.18);
INSERT INTO products(name,price,vat) VALUES ("egg",54,0.18);
INSERT INTO products(name,price,vat) VALUES ("dictionary",78,0.18);
INSERT INTO products(name,price,vat) VALUES ("vase",91,0.18);
INSERT INTO products(name,price,vat) VALUES ("hamster",1,0.18);
INSERT INTO products(name,price,vat) VALUES ("shawl",2,0.18);
INSERT INTO products(name,price,vat) VALUES ("clothes",70,0.18);
INSERT INTO products(name,price,vat) VALUES ("handful of change",79,0.18);
INSERT INTO products(name,price,vat) VALUES ("handheld game system",11,0.18);
INSERT INTO products(name,price,vat) VALUES ("balloon",73,0.18);
INSERT INTO products(name,price,vat) VALUES ("rolling pin",15,0.18);
INSERT INTO products(name,price,vat) VALUES ("bottle of nail polish",100,0.18);
INSERT INTO products(name,price,vat) VALUES ("bottle cap",25,0.18);
INSERT INTO products(name,price,vat) VALUES ("pair of knitting needles",66,0.18);
INSERT INTO products(name,price,vat) VALUES ("zebra",40,0.18);
INSERT INTO products(name,price,vat) VALUES ("helmet",99,0.18);
INSERT INTO products(name,price,vat) VALUES ("bookmark",50,0.18);
INSERT INTO products(name,price,vat) VALUES ("lamp shade",96,0.18);


INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Ayse Boyd',348,19,'2022-09-11');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Ioana Cote',652,3,'2022-10-12');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Garrett Benton',655,79,'2022-11-12');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Kelsi Terrell',599,5,'2022-09-05');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Saim Fuentes',155,32,'2022-11-05');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Charles Kumar',922,15,'2022-10-19');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Demi-Leigh Simon',523,57,'2022-09-04');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Leanne Hulme',536,19,'2022-10-17');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Leticia Lindsay',958,42,'2022-10-13');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Nikhil Brennan',263,92,'2022-09-18');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Ariya Schofield',813,67,'2022-10-30');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Paula Buxton',950,70,'2022-11-07');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Vinnie Hebert',254,45,'2022-08-22');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Elaina Guevara',775,73,'2022-08-17');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Pippa Grimes',219,83,'2022-09-20');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Livia Gilbert',903,60,'2022-08-15');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Zakir Weston',946,90,'2022-08-23');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Federico Sheppard',351,97,'2022-08-23');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Ayrton Dodson',768,58,'2022-08-18');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Maja Park',949,89,'2022-09-18');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Aisling Hendrix',422,7,'2022-09-27');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Halimah Bourne',141,53,'2022-10-31');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Damon Diaz',834,12,'2022-11-05');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Sarah Kelley',122,71,'2022-09-20');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Sonya Humphries',877,7,'2022-09-21');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Melisa Leigh',761,59,'2022-09-08');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Tony Bravo',391,97,'2022-10-25');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Christos Piper',170,29,'2022-11-09');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Marley Vinson',380,90,'2022-09-23');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Nour Deacon',966,25,'2022-09-19');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Zayn Fuller',841,56,'2022-10-21');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Krisha Searle',338,38,'2022-09-15');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Mohamad Underwood',825,85,'2022-09-25');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Leyton Hirst',443,44,'2022-10-13');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Sonny Mcguire',126,89,'2022-10-17');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Dominick Bryan',406,56,'2022-10-21');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Ieuan Wynn',737,5,'2022-08-26');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Talitha Baird',259,74,'2022-10-06');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Maurice Needham',587,1,'2022-11-07');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Summer Merritt',954,57,'2022-09-23');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Hugh Deleon',208,5,'2022-11-03');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Montgomery May',206,73,'2022-09-27');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Ravi Callaghan',836,55,'2022-09-22');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Sameera Olson',289,85,'2022-09-13');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Olivia Pearson',114,69,'2022-08-19');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Nakita Stokes',174,34,'2022-11-10');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Byron Philip',480,72,'2022-10-28');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Aislinn Villa',441,50,'2022-09-05');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Blair Crouch',939,52,'2022-09-06');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Patsy Couch',843,29,'2022-09-24');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Niam Goldsmith',415,26,'2022-11-06');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Hamaad Villalobos',795,59,'2022-10-21');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Veronika OQuinn',725,16,'2022-10-29');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Tahir Coulson',579,87,'2022-10-30');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Tate Henry',596,23,'2022-09-04');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Bodhi Prince',646,71,'2022-09-10');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Abdullah Ramirez',837,87,'2022-09-05');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Beatrix Justice',367,10,'2022-08-26');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Sharon Bryant',547,20,'2022-08-20');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Reiss Parkinson',439,21,'2022-11-06');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Evie-May Blankenship',775,96,'2022-09-21');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Michaela Squires',764,68,'2022-11-08');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Ptolemy Archer',477,39,'2022-10-26');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Margaux Campbell',463,58,'2022-10-02');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Corrie Roche',751,55,'2022-10-29');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Xena Freeman',208,50,'2022-11-07');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Carrie-Ann Southern',564,53,'2022-09-04');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Dawn Derrick',454,18,'2022-10-06');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Cem Simpson',529,51,'2022-10-16');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Rosanna Hopper',215,53,'2022-09-07');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Kianna Pearce',108,14,'2022-08-22');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Tyrique Clegg',947,94,'2022-08-24');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Myrtle Robin',940,27,'2022-10-14');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Noah Bernard',553,51,'2022-10-28');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Mayur Paul',524,78,'2022-10-01');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Jak Lang',397,7,'2022-08-21');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Hibah Ferry',707,1,'2022-09-19');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Kealan Moore',238,39,'2022-09-15');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Jaden Wicks',564,9,'2022-10-28');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Kurt Emery',437,67,'2022-09-14');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Luci Mcphee',891,87,'2022-09-15');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Sebastien Richardson',571,79,'2022-10-25');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Dainton Heath',997,55,'2022-10-26');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Arielle Barron',228,7,'2022-09-07');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Abbie Chamberlain',111,77,'2022-10-07');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Momina Dawe',200,47,'2022-09-17');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Aryaan Mooney',820,90,'2022-09-09');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Nuala Mcfarlane',495,76,'2022-09-06');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Aminah Knapp',750,18,'2022-09-18');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Mared Stone',265,90,'2022-10-04');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Christian Xiong',158,100,'2022-10-02');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Subhan Collins',766,31,'2022-08-15');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Gianluca Stubbs',463,77,'2022-09-05');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Deanne Burch',162,88,'2022-08-27');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Ace Choi',618,93,'2022-09-25');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Siena Blaese',155,68,'2022-10-09');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Saara Snider',109,80,'2022-09-02');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('James Bullock',281,75,'2022-09-20');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Josiah Ruiz',878,75,'2022-11-05');
INSERT INTO CUSTOMERS(NAME,BALANCE,CONSECUTIVE_DISCOUNT,HAS_SUBSEQUENT_DISCOUNT_UNTIL) VALUES ('Killian Jennings',455,21,'2022-08-20');
